source 'https://github.com/CocoaPods/Specs.git'

target 'TTPlayerSDK' do
  	pod 'IJKPlayerWithSSL'
    pod 'ksyhttpcache'
    pod 'FMDB'
  	pod 'TTAlertKit'
    pod 'CLTools'
    pod 'CLProgressFPD'
end
